apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q 
  name: q
  namespace: quarkus-1
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: q 

